[versions]
java                 = "16"
gjf                  = "1.11.0"
ktlint               = "0.42.1"
kotlin               = "1.5.31"
kotlin-api           = "1.5"
kotlinx-coroutines   = "1.5.2"
kotlinx-cli          = "0.3.2"
kotlin-ksp           = "1.5.31-1.0.0"
ktor                 = "1.6.3"

[libraries]
ktor-auth               = { module = "io.ktor:ktor-auth"                                , version.ref = "ktor"}
ktor-serialization      = { module = "io.ktor:ktor-serialization"                       , version.ref = "ktor"}
ktor-server-core        = { module = "io.ktor:ktor-server-core"                         , version.ref = "ktor" }
ktor-server-host-common = { module = "io.ktor:ktor-server-host-common"                  , version.ref = "ktor"}
ktor-server-netty       = { module = "io.ktor:ktor-server-netty"                        , version.ref = "ktor"}
ktor-server-tests       = { module = "io.ktor:ktor-server-tests"                        , version.ref = "ktor"}


[plugins]
kotlin-jvm              = { id = "org.jetbrains.kotlin.jvm"                              , version.ref = "kotlin" }
kotlinx-serialization   = { id = "org.jetbrains.kotlin.plugin.serialization"             , version.ref = "kotlin" }


