[versions]
java                           = "16"
kotlin                         = "1.6.0-RC"
kotlin-api                     = "1.6"
gradle                         = "7.3-rc-1"

# Gradle Dependencies Versions
benmanes                       = "0.39.0"
google-javaformat              = "1.11.0"
graalvm                        = "21.2.0"
graalvm-nativeimage            = "0.9.6"
jgitver                        = "0.10.0-rc03"
jreleaser                      = "0.7.0"
junit                          = "5.8.1"
junit-pioneer                  = "1.4.2"
kotlin-ksp                     = "1.5.31-1.0.0"
kotlinx-atomicfu               = "0.16.3"
kotlinx-coroutines             = "1.5.2"
kotlinx-collections-immutable  = "0.3.4"
kotlinx-cli                    = "0.3.2"
kotlinx-datetime               = "0.3.0"
kotlinx-reflect-lite           = "1.0.0"
kotlinx-io-jvm                 = "0.1.16"
kotlinx-serialization          = "1.3.0"
kotlinx-serialization-yaml     = "0.17.0"
kotlinx-serialization-csv      = "2.0.0"
ksp                            = "1.6.0-RC-1.0.0"
ksp-redacted                   = "0.8.0"
ktlint                         = "0.42.1"
ktor                           = "1.6.4"
logback-classic                = "1.2.6"
spotless                       = "5.16.0"

[libraries]
# Gradle Dependencies
graalvm-sdk                 = { module = "org.graalvm.sdk:graal-sdk"                        , version.ref = "graalvm"}
graalvm-svm                 = { module = "org.graalvm.nativeimage:svm"                      , version.ref = "graalvm"}
graalvm-svmlibffi           = { module = "org.graalvm.nativeimage:svm-libffi"               , version.ref = "graalvm"}

kotlinx-datetime                  = { module = "org.jetbrains.kotlinx:kotlinx-datetime"                  , version.ref = "kotlinx-datetime"}
kotlinx-atomicfu                  = { module = "org.jetbrains.kotlinx:atomicfu"                          , version.ref = "kotlinx-atomicfu"}
kotlinx-reflect-lite              = { module = "org.jetbrains.kotlinx:kotlinx.reflect.lite"              , version.ref = "kotlinx-reflect-lite"}
kotlinx-io-jvm                    = { module = "org.jetbrains.kotlinx:kotlinx-io-jvm"                    , version.ref = "kotlinx-io-jvm"}
kotlinx-cli                       = { module = "org.jetbrains.kotlinx:kotlinx-cli"                       , version.ref = "kotlinx-cli"}
kotlinx-collections-immutable     = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable-jvm" , version.ref = "kotlinx-collections-immutable"}
kotlinx-serialization-core        = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core"        , version.ref = "kotlinx-serialization"}
kotlinx-serialization-json        = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json"        , version.ref = "kotlinx-serialization"}
kotlinx-serialization-cbor        = { module = "org.jetbrains.kotlinx:kotlinx-serialization-cbor"        , version.ref = "kotlinx-serialization"}
kotlinx-serialization-hocon       = { module = "org.jetbrains.kotlinx:kotlinx-serialization-hocon"       , version.ref = "kotlinx-serialization"}
kotlinx-serialization-protobuf    = { module = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf"    , version.ref = "kotlinx-serialization"}
kotlinx-serialization-properties  = { module = "org.jetbrains.kotlinx:kotlinx-serialization-properties"  , version.ref = "kotlinx-serialization"}
kotlinx-serialization-yaml        = { module = "com.charleskorn.kaml:kaml"                               , version.ref = "kotlinx-serialization-yaml"}
kotlinx-serialization-csv         = { module = "de.brudaswen.kotlinx.serialization:kotlinx-serialization-csv" , version.ref = "kotlinx-serialization-csv"}

ktor-server                 = { module = "io.ktor:ktor-server-core"                         , version.ref = "ktor"}
ktor-auth                   = { module = "io.ktor:ktor-auth"                                , version.ref = "ktor"}
ktor-serialization          = { module = "io.ktor:ktor-serialization"                       , version.ref = "ktor"}
ktor-server-host-common     = { module = "io.ktor:ktor-server-host-common"                  , version.ref = "ktor"}
ktor-server-netty           = { module = "io.ktor:ktor-server-netty"                        , version.ref = "ktor"}
ktor-server-tests           = { module = "io.ktor:ktor-server-tests"                        , version.ref = "ktor"}

ktor-client                 = { module = "io.ktor:ktor-client-core"                         , version.ref = "ktor"}
ktor-client-cio             = { module = "io.ktor:ktor-client-cio"                          , version.ref = "ktor"}
ktor-client-java            = { module = "io.ktor:ktor-client-java"                         , version.ref = "ktor"}
ktor-client-jetty           = { module = "io.ktor:ktor-client-jetty"                        , version.ref = "ktor"}
ktor-client-serialization   = { module = "io.ktor:ktor-client-serialization"                , version.ref = "ktor"}
ktor-client-websockets      = { module = "io.ktor:ktor-client-websockets"                   , version.ref = "ktor"}
ktor-client-auth            = { module = "io.ktor:ktor-client-auth"                         , version.ref = "ktor"}
ktor-client-logging         = { module = "io.ktor:ktor-client-logging"                      , version.ref = "ktor"}


junit-bom                   = { module = "org.junit:junit-bom"                        , version.ref = "junit"}
junit-jupiter               = { module = "org.junit.jupiter:junit-jupiter"            , version.ref = "junit"}
junit-jupiter-api           = { module = "org.junit.jupiter:junit-jupiter-api"        , version.ref = "junit"}
junit-jupiter-engine        = { module = "org.junit.jupiter:junit-jupiter-engine"     , version.ref = "junit"}
junit-jupiter-params        = { module = "org.junit.jupiter:junit-jupiter-params"     , version.ref = "junit"}
junit-pioneer               = { module = "org.junit-pioneer:junit-pioneer"            , version.ref = "junit-pioneer"}

logback-classic             = { module = "ch.qos.logback:logback-classic"             , version.ref = "logback-classic"}


[plugins]
# Gradle  Plugins
benmanes                    = { id = "com.github.ben-manes.versions"                         , version.ref = "benmanes" }
graalvm-nativeimage         = { id = "org.graalvm.buildtools.native"                         , version.ref = "graalvm-nativeimage"}
jgitver                     = { id = "fr.brouillard.oss.gradle.jgitver"                      , version.ref = "jgitver" }
jreleaser                   = { id = "org.jreleaser"                                         , version.ref = "jreleaser" }
kotlin-jvm                  = { id = "org.jetbrains.kotlin.jvm"                              , version.ref = "kotlin" }
kotlinx-serialization       = { id = "org.jetbrains.kotlin.plugin.serialization"             , version.ref = "kotlin" }
ksp                         = { id = "com.google.devtools.ksp"                               , version.ref = "ksp"}
ksp-redacted                = { id = "dev.zacsweers.redacted"                                , version.ref = "ksp-redacted" }
spotless                    = { id = "com.diffplug.spotless"                                 , version.ref = "spotless" }

[bundles]
ktor-server                 = ["ktor-server", "ktor-serialization", "ktor-auth", "ktor-server-host-common", "ktor-server-netty", "logback-classic"]
ktor-client                 = ["ktor-client", "ktor-client-java", "ktor-client-serialization", "ktor-client-logging", "logback-classic"]


